AWSTemplateFormatVersion: "2010-09-09"

Description:
  Setup ECS Cluster
Resources:
  ECSCluster: # THe LogicalName 
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: Fo_Cluster
      CapacityProviders:
        - FARGATE


# Parameters:
# Mappings:
# Outputs:
# Metadata:
# Rules:
